FROM continuumio/miniconda3:23.10.0-1
RUN conda install -c conda-forge -c bioconda bwa-mem2=2.2.1 samtools=1.19 \
    bellerophon=1.0 pretext-suite=0.0.2 pretextgraph=0.0.6 pretextmap=0.1.9 \
    pretextsnapshot=0.0.4 python=3.10 -y